version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./.env:/home/node/app/.env
      - ./prisma:/home/node/app/prisma
    container_name: ts-node-docker
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
  redis:
    image: redis
    command: redis-server --requirepass admin!
    ports:
      - 6379:6379

