FROM node:14
WORKDIR /usr
COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src
COPY prisma ./prisma
RUN ls -a
RUN npm install
RUN npm install @prisma/client
RUN npx prisma generate
EXPOSE 4005
CMD ["npm","run","dev"]